# Generated by Django 3.2.4 on 2021-06-30 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_link', models.URLField(max_length=5000)),
                ('pagerank', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
