# Generated by Django 3.2.4 on 2021-07-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Searches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string', models.CharField(max_length=1000)),
                ('frequency', models.IntegerField(default=0)),
            ],
        ),
    ]
